auth:
  jwt: 
    secret: 'fysw6gf3k@'
    expiration: '8h'

db:
  mysql: 
      type: 'mysql'
      host: 'localhost'
      port: 3307
      username: 'root'
      password: 'password'
      database: 'licenta'
      entities: ['dist/**/*.model{.ts,.js}'']
      synchronize: true
 