auth:
  jwt: 
    secret: 'fysw6gf3k@'
    expiration: '8h'

sentiment: 
  languages: 
    supported: ['en', 'ro']
    selected: ['ro']

db:
  mysql: 
      type: 'mysql'
      host: 'localhost'
      port: 3307
      username: 'root'
      password: 'password'
      database: 'licenta'
      entities: ['dist/**/*.entity{.ts,.js}']
      synchronize: true
 